### ISSUE TITLE
[Bug]: Settings.json was not created.

### ISSUE THREAD

**Issue by emf37** [MDModsDev/MuseDashModToolsUI#130]
### I'm using the latest build release of Muse Dash Mod Tools and this problem still exists.

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### Operating system

Windows 10 and below

### Bug Detail

hello, 

I've got an issue with the latest version (1.2.2), hopefully this helps!

MuseDashModTools will ask for the MuseDash installation path every time you start MuseDashModTools and the settings on the Settings page will not be saved in the local Settings.json. 

No configuration information will be written if you create Settings.json in the folder where MuseDashModTools.exe is located.

### Logs

[2023-10-01_23-50-08.log](https://github.com/MDModsDev/MuseDashModToolsUI/files/12777540/2023-10-01_23-50-08.log)

**Comment by lxymahatma** [comment]
i think it's fixed with 1.2.3 release 👀
