### ISSUE TITLE
[Help Wanted]: Program text missing/corrupted(?)

### ISSUE THREAD

**Issue by maksemakes** [MDModsDev/MuseDashModToolsUI#162]
### Operating system

Windows 10 and below

### Problem Detail (Optional)

When I run the program the entire application text is missing. The program has worked for me in the past, but it seems broken after the recent Muse Dash update. Even downgrading doesn't seem to fix the issue. I'm not exactly sure what could be wrong with it or if I am missing any dependencies. I uninstalled and reinstalled the game along with MelonLoader and it is still not working. Thank you so much for all you do and sorry to be a bother!

### Screenshots (Optional)

![image](https://github.com/MDModsDev/MuseDashModToolsUI/assets/109233571/095d6093-47db-4303-8b1b-53fa73341d9a)

### Logs

[2023-10-13_21-07-57.log](https://github.com/MDModsDev/MuseDashModToolsUI/files/12901013/2023-10-13_21-07-57.log)

**Comment by lxymahatma** [comment]
i think it's due to font problem, the font u are using don't have the characters in ur language, u can configure font in fourth tab

**Comment by maksemakes** [comment]
![image](https://github.com/MDModsDev/MuseDashModToolsUI/assets/109233571/2176f002-b2ff-4f92-a5a5-5a7536244119)
Where would that option be? I believe I'm using just the regular Windows font and the English language pack.

**Comment by lxymahatma** [comment]
> ![image](https://github.com/MDModsDev/MuseDashModToolsUI/assets/109233571/2176f002-b2ff-4f92-a5a5-5a7536244119)
> Where would that option be? I believe I'm using just the regular Windows font and the English language pack.

there's a screen shot in readme,
should be the second one with dropdown and a button. hmmm if u are using regular font and English then that's weird

**Comment by maksemakes** [comment]
Okay I managed to fix it after just randomly selecting languages and fonts. When I set it to ru and a random font, the text came back. Thank you!

**Comment by lxymahatma** [comment]
> Okay I managed to fix it after just randomly selecting languages and fonts. When I set it to ru and a random font, the text came back. Thank you!

👍🏻glad to hear that
