### ISSUE TITLE
[Feature Request]: Launch Muse Dash

### ISSUE THREAD

**Issue by MinecraftNight4** [MDModsDev/MuseDashModToolsUI#184]
### Brief Introduction

A button to launch Muse Dash directly from the menu.

### Details

It would be useful to have a button on the top bar to launch Muse Dash, without having to use Steam.
`steam://run/774171/`

And in the settings menu, some text bar to add Steam launch parameters:
[MelonLoader Launch Arguments](https://melonwiki.xyz/#/?id=launch-arguments)

**Comment by lxymahatma** [comment]
already did in ui rewrite branch, but i don't have much time to design a ui so u'll see it after a long long time
