### ISSUE TITLE
[Help Wanted]: All mods are incompatible, they are all red in color

### ISSUE THREAD

**Issue by xiaoxiao1232** [MDModsDev/MuseDashModToolsUI#229]
### Operating system

Windows 11

### Problem Detail (Optional)

 All mods are incompatible, they are all red in color

### Screenshots (Optional)

![屏幕截图 2024-01-06 000420](https://github.com/MDModsDev/MuseDashModToolsUI/assets/155757047/fa394d3c-e1a3-4c77-870c-07e78430b14b)

### Logs

![Uploading 屏幕截图 2024-01-06 000420.png…]()

**Comment by lxymahatma** [comment]
mods not working on the latest md version, warnings are correct

**Comment by xiaoxiao1232** [comment]
How can I solve this problem

**Comment by xiaoxiao1232** [comment]
> mods not working on the latest md version, warnings are correct
How can I solve this problem

**Comment by lxymahatma** [comment]
> > mods not working on the latest md version, warnings are correct
> > How can I solve this problem

wait for updates
