### ISSUE TITLE
[Bug]:  所有的mod都不兼容，都是红色的 所有的mod都不兼容，都是红色的​ All mods are incompatible, they are all red in color

### ISSUE THREAD

**Issue by xiaoxiao1232** [MDModsDev/MuseDashModToolsUI#230]
### I'm using the latest build release of Muse Dash Mod Tools and this problem still exists.

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### Operating system

Windows 11

### Bug Detail

所有的mod都不兼容，都是红色的
所有的mod都不兼容，都是红色的​
All mods are incompatible, they are all red in color

### Screenshots (Optional)

![屏幕截图 2024-01-06 000420](https://github.com/MDModsDev/MuseDashModToolsUI/assets/155757047/449d78dd-e177-4106-ad72-162aa6febb16)

### Logs

![Uploading 屏幕截图 2024-01-06 000420.png…]()

**Comment by lxymahatma** [comment]
same with #229
