### ISSUE TITLE
[Help Wanted]: All mods are incompatible, they are all red. The game version is the latest, and none of the mods have been downloaded. They are still red

### ISSUE THREAD

**Issue by xiaoxiao1232** [MDModsDev/MuseDashModToolsUI#231]
### Operating system

Windows 11

### Problem Detail (Optional)

All mods are incompatible, they are all red. The game version is the latest, and none of the mods have been downloaded. They are still red

### Screenshots (Optional)

![屏幕截图 2024-01-06 001751](https://github.com/MDModsDev/MuseDashModToolsUI/assets/155757047/2c5e7592-fe7d-44a3-b5d4-59e54c08ade1)

### Logs

![Uploading 屏幕截图 2024-01-06 001751.png…]()

**Comment by lxymahatma** [comment]
same with #229
