### ISSUE TITLE
"Re-install" results in malformed file

### ISSUE THREAD

**Issue by Balint817** [MDModsDev/MuseDashModToolsUI#5]
Title.
Re-install a modified mod and relaunch modtools. Modtools will say that the file is modified.

Additionally,
Update an outdated mod, and relaunch modtools. Modtools behaves as expected, the file is unmodified.

**Comment by lxymahatma** [comment]
tried with ultra instinct sleepwalking, reinstall doesn't cause mod tools shows modified  after relaunch
might be fixed by other commits in dev branch
or maybe just a specific mod causes the problem
